// Souffle - A Datalog Compiler
// Copyright (c) 2018, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Dedicated test for hash-based sets to ensure relations are being stored/accessed correctly.

.decl A(x:number, y:number, z:number) rbtset 
A(1,1,1).
A(1,1,2).
A(x+z+a,y-z+b,z+1) :- A(x,y,z),  A(a,b,z-1), z < 10.
.decl B(x:number, y:number, z:number) hashset 
B(1,1,1).
B(1,1,2).
B(x+z+a,y-z+b,z+1) :- B(x,y,z),  B(a,b,z-1), z < 10.

// Test nullary relations
.decl C(x:number)
C(0).
.decl D() rbtset
D() :- C(0).
.decl E() hashset
E() :- C(0).

.output A, B, D, E
